### ISSUE TITLE
Impossible de se connecter au serveur d'intégration

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/riot_ynh#7]
Bonjour

J'ai installé riot mais quand je veux rajouter une nouvelle intégration j'ai le message impossible de se connecter au serveur d'intégration

Merci d'avance pour votre aide

**Comment by Josue-T** [comment]
Hello,

Do you have any filter in your brower like noscript, etc. Because it could block that.

**Comment by Rafi594** [comment]
No I have no adblocker or noscript plugin on my browser

**Comment by Josue-T** [comment]
Witch synapse package do you have ?

**Comment by Rafi594** [comment]
https://github.com/YunoHost-Apps/synapse_ynh 

Latest version

**Comment by Josue-T** [comment]
I remember that where are some weeks ago I had the same problem but actually it is solved on my side. So I don't really know how to help you about this issue.

Mybe you could try to open a console in your browser to see what is happening about that.
An other thing is that the app is not up to date in this list `https://github.com/YunoHost/apps/blob/master/community.json` so if you want to have this app up to date you need to update by the url.

**Comment by Rafi594** [comment]
I have tried to upgrade synapse but my server doesn't responding and I get this errors

```
Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.429338] fe40: a8676740 80108244 80d3e000 00000000 80d3fe8c 80d3fe60 8012b270 8012adbc

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.429441] fe60: 00000000 80d3fe70 8012bcc8 00000001 a8676740 00000001 80d3fef8 00000002

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.429545] fe80: 80d3feb4 80d3fe90 8012bee8 8012b234 00000000 20000013 00000002 a8676740

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.429649] fea0: 80d3fef8 00000025 80d3fed4 80d3feb8 8012c110 8012bea4 00000002 81974f40

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.429750] fec0: 80d3fef8 00000002 80d3fef4 80d3fed8 8012c248 8012c0cc 81974f5c 000055a2

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.429857] fee0: 00000000 00000002 80d3ffa4 80d3fef8 8012ded4 8012c214 00000002 00000000

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.429963] ff00: 00000000 000055a2 000003e8 80d3e000 7e8c4748 7e8c4640 41034034 00000000

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.430067] ff20: 80d3e000 00000000 80d3ff44 80d3ff38 80461de4 80461b3c 80d3ff64 80d3ff48

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.430171] ff40: 80103088 80461dd0 7e8c4550 80d3ffb0 00000000 00000077 80d3ff8c 00000002

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.430276] ff60: 8010af50 00000001 80d3e010 00000000 80d3ffb0 00000001 00000000 00000001

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.430380] ff80: 00000000 00012d60 00000025 80108244 80d3e000 00000000 00000000 80d3ffa8

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.430482] ffa0: 801080c0 8012de4c 00000001 00000000 000055a2 00000002 76f016d0 000055a2

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.430587] ffc0: 00000001 00000000 00012d60 00000025 00000007 00000000 7c967e3f 76f05d98

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.430691] ffe0: 000ee1ec 7e8c454c 76d2f180 76d2e1ec 20000010 000055a2 00000000 00000000

Message from syslogd@YunoHost at Oct 30 22:12:58 ...
 kernel:[32115.457157] Code: e5940474 e592100c e5902068 e5911478 (e5910068) 
```

**Comment by Josue-T** [comment]
Witch architecture do you have ?

**Comment by Rafi594** [comment]
Raspberry Pi 3

**Comment by Josue-T** [comment]
Ok, and can you reboot ? Mybe it could solve the problem.
It it a arm64 arch ?

**Comment by Rafi594** [comment]
I have retried to upgrade synapse and I works I have the latest version but the riot problem is not solved

**Comment by Rafi594** [comment]
![](https://framapic.org/mHCxT6nx6pOz/ZqKYMPT82lJ5)

**Comment by Josue-T** [comment]
Ok, happy to know that the upgrade has been sucessfull.
About the integration function have you tried to see in the browser console ?

**Comment by Rafi594** [comment]
Error whilst initialising scalarClient for ManageIntegsButton Error: CORS request rejected: https://scalar.vector.im/api/register
Trace de la pile :
o@https://domain.tld/riot/bundles/b6299...b52/bundle.js:14:26480
r@https://domain.tld/riot/bundles/b6299a7...d5b52/bundle.js:14:26227
  rageshake.js:65:16

**Comment by Rafi594** [comment]
Failed to connect to integrations server  rageshake.js:65:16
Persisting sync data up to  s642_152163_0_834_72_1_1_297_1  indexeddb-worker.js:4:27523
Starting load of AsyncWrapper for modal  rageshake.js:65:16
AsyncWrapper load completed with IntegrationsManager  rageshake.js:65:16

**Comment by Rafi594** [comment]
Probably a problem with the nginx configuration

**Comment by Josue-T** [comment]
Mybe this problem could comme if your homeserver is not accessible from the federation mybe. So could you check that your homeserver is accessible from everywhere on the port 8448.

**Comment by Josue-T** [comment]
To diagnosis your problem you could also access to your homeserver from the official riot app. So for that, go on https://riot.im/app/#/login and set the `custom server` option and in the `Home server URL` set your server url on the port 8448, like `https://domain.tld:8448`.

If in this case it's ok, the problem should be on the homeserver side. If not redo this test but set the homeserver on the port 443.

**Comment by Rafi594** [comment]
I have make the app public and it works fine now

**Comment by Josue-T** [comment]
Have you solved your issue ?

**Comment by Rafi594** [comment]
Yes It works fine now
