### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/riot_ynh#8]
hi, 
the installation failed as it couldn't find/create the user root:root
Here is detailed log. Only my domain has been replaced by domain.tld 

https://paste.yunohost.org/fipezidomi.sql

Thanks for the help

**Comment by Josue-T** [comment]
Thank you for your issue,

It's fixed by e35402df2e52f42a2e384ea173e6ff5c5ff5ca68
